// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK                 Code = 0
	Code_CLIENT_ID_REQUIRED Code = 1
	Code_SHARD_NOT_FOUND    Code = 2
	Code_SHARD_FENCED       Code = 3
	Code_ENTRY_NOT_FOUND    Code = 4
	Code_READ_EXCEPTION     Code = 5
	Code_METADATA_EXCEPTION Code = 6
	Code_WRITE_EXCEPTION    Code = 7
	Code_NO_NODE_AVAILABLE  Code = 8
	Code_DEVICE_EXCEPTION   Code = 9
	Code_NOT_SHARD_LEADER   Code = 10
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "OK",
		1:  "CLIENT_ID_REQUIRED",
		2:  "SHARD_NOT_FOUND",
		3:  "SHARD_FENCED",
		4:  "ENTRY_NOT_FOUND",
		5:  "READ_EXCEPTION",
		6:  "METADATA_EXCEPTION",
		7:  "WRITE_EXCEPTION",
		8:  "NO_NODE_AVAILABLE",
		9:  "DEVICE_EXCEPTION",
		10: "NOT_SHARD_LEADER",
	}
	Code_value = map[string]int32{
		"OK":                 0,
		"CLIENT_ID_REQUIRED": 1,
		"SHARD_NOT_FOUND":    2,
		"SHARD_FENCED":       3,
		"ENTRY_NOT_FOUND":    4,
		"READ_EXCEPTION":     5,
		"METADATA_EXCEPTION": 6,
		"WRITE_EXCEPTION":    7,
		"NO_NODE_AVAILABLE":  8,
		"DEVICE_EXCEPTION":   9,
		"NOT_SHARD_LEADER":   10,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_storage_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_proto_storage_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

type BatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Requests      []*PutRequest          `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
	mi := &file_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutRequest.ProtoReflect.Descriptor instead.
func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *BatchPutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BatchPutRequest) GetRequests() []*PutRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchPutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key means entryId
	Responses     map[uint32]*PutResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutResponse) Reset() {
	*x = BatchPutResponse{}
	mi := &file_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutResponse) ProtoMessage() {}

func (x *BatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutResponse.ProtoReflect.Descriptor instead.
func (*BatchPutResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *BatchPutResponse) GetResponses() map[uint32]*PutResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ShardId       uint64                 `protobuf:"varint,2,opt,name=shardId,proto3" json:"shardId,omitempty"`
	EntryId       uint32                 `protobuf:"varint,3,opt,name=entryId,proto3" json:"entryId,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Indexes       []*Index               `protobuf:"bytes,5,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PutRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *PutRequest) GetEntryId() uint32 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Index) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Index) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=storage.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{4}
}

func (x *PutResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	EntryId       uint32                 `protobuf:"varint,2,opt,name=entryId,proto3" json:"entryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *GetRequest) GetEntryId() uint32 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=storage.Code" json:"code,omitempty"`
	ShardId       uint64                 `protobuf:"varint,2,opt,name=shardId,proto3" json:"shardId,omitempty"`
	EntryId       uint32                 `protobuf:"varint,3,opt,name=entryId,proto3" json:"entryId,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *GetResponse) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *GetResponse) GetEntryId() uint32 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	EntryIds      []uint32               `protobuf:"varint,2,rep,packed,name=entryIds,proto3" json:"entryIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_proto_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *BatchGetRequest) GetEntryIds() []uint32 {
	if x != nil {
		return x.EntryIds
	}
	return nil
}

type NewShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewShardRequest) Reset() {
	*x = NewShardRequest{}
	mi := &file_proto_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewShardRequest) ProtoMessage() {}

func (x *NewShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewShardRequest.ProtoReflect.Descriptor instead.
func (*NewShardRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{8}
}

func (x *NewShardRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type NewShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=storage.Code" json:"code,omitempty"`
	ShardId       uint64                 `protobuf:"varint,2,opt,name=shardId,proto3" json:"shardId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewShardResponse) Reset() {
	*x = NewShardResponse{}
	mi := &file_proto_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewShardResponse) ProtoMessage() {}

func (x *NewShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewShardResponse.ProtoReflect.Descriptor instead.
func (*NewShardResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{9}
}

func (x *NewShardResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *NewShardResponse) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type DeleteShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShardRequest) Reset() {
	*x = DeleteShardRequest{}
	mi := &file_proto_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardRequest) ProtoMessage() {}

func (x *DeleteShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardRequest.ProtoReflect.Descriptor instead.
func (*DeleteShardRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteShardRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type DeleteShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=storage.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShardResponse) Reset() {
	*x = DeleteShardResponse{}
	mi := &file_proto_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardResponse) ProtoMessage() {}

func (x *DeleteShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardResponse.ProtoReflect.Descriptor instead.
func (*DeleteShardResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteShardResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

type CloseShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShardRequest) Reset() {
	*x = CloseShardRequest{}
	mi := &file_proto_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShardRequest) ProtoMessage() {}

func (x *CloseShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShardRequest.ProtoReflect.Descriptor instead.
func (*CloseShardRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{12}
}

func (x *CloseShardRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type CloseShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=storage.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShardResponse) Reset() {
	*x = CloseShardResponse{}
	mi := &file_proto_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShardResponse) ProtoMessage() {}

func (x *CloseShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShardResponse.ProtoReflect.Descriptor instead.
func (*CloseShardResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{13}
}

func (x *CloseShardResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

var File_proto_storage_proto protoreflect.FileDescriptor

const file_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x13proto/storage.proto\x12\astorage\"^\n" +
	"\x0fBatchPutRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12/\n" +
	"\brequests\x18\x02 \x03(\v2\x13.storage.PutRequestR\brequests\"\xae\x01\n" +
	"\x10BatchPutResponse\x12F\n" +
	"\tresponses\x18\x01 \x03(\v2(.storage.BatchPutResponse.ResponsesEntryR\tresponses\x1aR\n" +
	"\x0eResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.storage.PutResponseR\x05value:\x028\x01\"\x9c\x01\n" +
	"\n" +
	"PutRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\ashardId\x18\x02 \x01(\x04R\ashardId\x12\x18\n" +
	"\aentryId\x18\x03 \x01(\rR\aentryId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12(\n" +
	"\aindexes\x18\x05 \x03(\v2\x0e.storage.IndexR\aindexes\"/\n" +
	"\x05Index\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"0\n" +
	"\vPutResponse\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.storage.CodeR\x04code\"@\n" +
	"\n" +
	"GetRequest\x12\x18\n" +
	"\ashardId\x18\x01 \x01(\x04R\ashardId\x12\x18\n" +
	"\aentryId\x18\x02 \x01(\rR\aentryId\"z\n" +
	"\vGetResponse\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.storage.CodeR\x04code\x12\x18\n" +
	"\ashardId\x18\x02 \x01(\x04R\ashardId\x12\x18\n" +
	"\aentryId\x18\x03 \x01(\rR\aentryId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"G\n" +
	"\x0fBatchGetRequest\x12\x18\n" +
	"\ashardId\x18\x01 \x01(\x04R\ashardId\x12\x1a\n" +
	"\bentryIds\x18\x02 \x03(\rR\bentryIds\"-\n" +
	"\x0fNewShardRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\"O\n" +
	"\x10NewShardResponse\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.storage.CodeR\x04code\x12\x18\n" +
	"\ashardId\x18\x02 \x01(\x04R\ashardId\".\n" +
	"\x12DeleteShardRequest\x12\x18\n" +
	"\ashardId\x18\x01 \x01(\x04R\ashardId\"8\n" +
	"\x13DeleteShardResponse\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.storage.CodeR\x04code\"-\n" +
	"\x11CloseShardRequest\x12\x18\n" +
	"\ashardId\x18\x01 \x01(\x04R\ashardId\"7\n" +
	"\x12CloseShardResponse\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.storage.CodeR\x04code*\xe6\x01\n" +
	"\x04Code\x12\x06\n" +
	"\x02OK\x10\x00\x12\x16\n" +
	"\x12CLIENT_ID_REQUIRED\x10\x01\x12\x13\n" +
	"\x0fSHARD_NOT_FOUND\x10\x02\x12\x10\n" +
	"\fSHARD_FENCED\x10\x03\x12\x13\n" +
	"\x0fENTRY_NOT_FOUND\x10\x04\x12\x12\n" +
	"\x0eREAD_EXCEPTION\x10\x05\x12\x16\n" +
	"\x12METADATA_EXCEPTION\x10\x06\x12\x13\n" +
	"\x0fWRITE_EXCEPTION\x10\a\x12\x15\n" +
	"\x11NO_NODE_AVAILABLE\x10\b\x12\x14\n" +
	"\x10DEVICE_EXCEPTION\x10\t\x12\x14\n" +
	"\x10NOT_SHARD_LEADER\x10\n" +
	"2\xc5\x03\n" +
	"\x0eStorageService\x120\n" +
	"\x03Put\x12\x13.storage.PutRequest\x1a\x14.storage.PutResponse\x12?\n" +
	"\bBatchPut\x12\x18.storage.BatchPutRequest\x1a\x19.storage.BatchPutResponse\x120\n" +
	"\x03Get\x12\x13.storage.GetRequest\x1a\x14.storage.GetResponse\x12<\n" +
	"\bBatchGet\x12\x18.storage.BatchGetRequest\x1a\x14.storage.GetResponse0\x01\x12?\n" +
	"\bNewShard\x12\x18.storage.NewShardRequest\x1a\x19.storage.NewShardResponse\x12H\n" +
	"\vDeleteShard\x12\x1b.storage.DeleteShardRequest\x1a\x1c.storage.DeleteShardResponse\x12E\n" +
	"\n" +
	"CloseShard\x12\x1a.storage.CloseShardRequest\x1a\x1b.storage.CloseShardResponseB$Z\"github.com/debs/debs/proto;storageb\x06proto3"

var (
	file_proto_storage_proto_rawDescOnce sync.Once
	file_proto_storage_proto_rawDescData []byte
)

func file_proto_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)))
	})
	return file_proto_storage_proto_rawDescData
}

var file_proto_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_storage_proto_goTypes = []any{
	(Code)(0),                   // 0: storage.Code
	(*BatchPutRequest)(nil),     // 1: storage.BatchPutRequest
	(*BatchPutResponse)(nil),    // 2: storage.BatchPutResponse
	(*PutRequest)(nil),          // 3: storage.PutRequest
	(*Index)(nil),               // 4: storage.Index
	(*PutResponse)(nil),         // 5: storage.PutResponse
	(*GetRequest)(nil),          // 6: storage.GetRequest
	(*GetResponse)(nil),         // 7: storage.GetResponse
	(*BatchGetRequest)(nil),     // 8: storage.BatchGetRequest
	(*NewShardRequest)(nil),     // 9: storage.NewShardRequest
	(*NewShardResponse)(nil),    // 10: storage.NewShardResponse
	(*DeleteShardRequest)(nil),  // 11: storage.DeleteShardRequest
	(*DeleteShardResponse)(nil), // 12: storage.DeleteShardResponse
	(*CloseShardRequest)(nil),   // 13: storage.CloseShardRequest
	(*CloseShardResponse)(nil),  // 14: storage.CloseShardResponse
	nil,                         // 15: storage.BatchPutResponse.ResponsesEntry
}
var file_proto_storage_proto_depIdxs = []int32{
	3,  // 0: storage.BatchPutRequest.requests:type_name -> storage.PutRequest
	15, // 1: storage.BatchPutResponse.responses:type_name -> storage.BatchPutResponse.ResponsesEntry
	4,  // 2: storage.PutRequest.indexes:type_name -> storage.Index
	0,  // 3: storage.PutResponse.code:type_name -> storage.Code
	0,  // 4: storage.GetResponse.code:type_name -> storage.Code
	0,  // 5: storage.NewShardResponse.code:type_name -> storage.Code
	0,  // 6: storage.DeleteShardResponse.code:type_name -> storage.Code
	0,  // 7: storage.CloseShardResponse.code:type_name -> storage.Code
	5,  // 8: storage.BatchPutResponse.ResponsesEntry.value:type_name -> storage.PutResponse
	3,  // 9: storage.StorageService.Put:input_type -> storage.PutRequest
	1,  // 10: storage.StorageService.BatchPut:input_type -> storage.BatchPutRequest
	6,  // 11: storage.StorageService.Get:input_type -> storage.GetRequest
	8,  // 12: storage.StorageService.BatchGet:input_type -> storage.BatchGetRequest
	9,  // 13: storage.StorageService.NewShard:input_type -> storage.NewShardRequest
	11, // 14: storage.StorageService.DeleteShard:input_type -> storage.DeleteShardRequest
	13, // 15: storage.StorageService.CloseShard:input_type -> storage.CloseShardRequest
	5,  // 16: storage.StorageService.Put:output_type -> storage.PutResponse
	2,  // 17: storage.StorageService.BatchPut:output_type -> storage.BatchPutResponse
	7,  // 18: storage.StorageService.Get:output_type -> storage.GetResponse
	7,  // 19: storage.StorageService.BatchGet:output_type -> storage.GetResponse
	10, // 20: storage.StorageService.NewShard:output_type -> storage.NewShardResponse
	12, // 21: storage.StorageService.DeleteShard:output_type -> storage.DeleteShardResponse
	14, // 22: storage.StorageService.CloseShard:output_type -> storage.CloseShardResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_storage_proto_init() }
func file_proto_storage_proto_init() {
	if File_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_proto_depIdxs,
		EnumInfos:         file_proto_storage_proto_enumTypes,
		MessageInfos:      file_proto_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_proto = out.File
	file_proto_storage_proto_goTypes = nil
	file_proto_storage_proto_depIdxs = nil
}
